### ISSUE TITLE
Versions Tag

### ISSUE THREAD

**Issue by oOHiyoriOo** [Jannyboy11/InvSee-plus-plus#103]
I'm sorry to bother you, but could you please tag working minecraft versions in the releases? 
Currently seeking for one that works with 1.20.1, but I just have to try a guess as there's no information available as it seems what version run on what game version.

**Comment by Jannyboy11** [comment]
Technically this information is already available. the README.md contains a supported-server-software section: https://github.com/Jannyboy11/InvSee-plus-plus?tab=readme-ov-file#supported-server-software. So if you download a release from the [releases](https://github.com/Jannyboy11/InvSee-plus-plus/releases/) the README.md of that release will tell you the supported Minecraft versions.

If you run the plugin on a server which is not the right version, the plugin will suggest you which server software to use instead, or which version of InvSee++ to use instead such that it's compatible with the server. You can find the code for it here: https://github.com/Jannyboy11/InvSee-plus-plus/blob/master/InvSee%2B%2B_Common/src/main/java/com/janboerman/invsee/spigot/internal/version/LegacyVersions.java#L10. 

The reason I don't post this publicly in the repository and on SpigotMC is because I don't want to encourage users to use server software which is itself no longer maintained.
