### ISSUE TITLE
/invsee on offline players causes their OfflinePlayer#getLastPlayed() to update

### ISSUE THREAD

**Issue by epserv** [Jannyboy11/InvSee-plus-plus#13]
When you use `/invsee` on some offline player, their last played time updates to the time you opened their inventory.

This also creates player's .dat file even if player has never played on the server before and person who used `/invsee` didn't put anything to that offline player's inventory.

**Comment by Jannyboy11** [comment]
The player's .dat file is created if none exists, because one use case of this plugin is that you can already edit inventories of players even before they have logged in for the first time. Consequently, their 'last played'-time is updated too. Not really much I can do there.

Did you test whether the last-played time updated too when the player's data file already existed?

**Comment by epserv** [comment]
> Did you test whether the last-played time updated too when the player's data file already existed?

@Jannyboy11 yes, I did, it still gets updated to the time when /invsee was used (or saved? didn't test when exactly) even if player's `.dat` file already exists and this player exists too.

**Comment by Jannyboy11** [comment]
I need to investigate whether I can fix this, but never in my own code do I write out a last-played value to the player's save-file, so I suppose this is done by the save mechanism itself. I will need to investigate whether I can find a proper solution.
