### ISSUE TITLE
Support for Magma 1.16.5

### ISSUE THREAD

**Issue by golfista** [Jannyboy11/InvSee-plus-plus#43]
it doesnt work

**Comment by Jannyboy11** [comment]
Okay, I see what is the issue. I will see if I can find a fix this afternoon.

**Comment by Jannyboy11** [comment]
It seems that Magma has a remapping bug, as Magma 1.16.5 is discontinued, I would recommend the Mohist server software. I will still see if I can make it work on Magma though.

**Comment by golfista** [comment]
I see, appreciate you for trying fixing this problem

**Comment by Jannyboy11** [comment]
The bug in Magma is that it doesn't remap methods of types in plugin inherited from NMS types. So if I want to make it work on Magma, I would have to reimplement all methods of MainNmsInventory, MainNmsContainer, EnderNmsInventory and EnderNmsContainer, but using their obfuscated SRG-names. This is a lot of effort, so I won't be done with this any time soon. I'm still considering whether I should actually do this at all, since this is really a bug in Magma.

**Comment by Jannyboy11** [comment]
Ok, I decided to fix this. New release within an hour. But I think you're still better off using Mohist, since other plugins that utilise NMS are likely to break as well.

**Comment by Jannyboy11** [comment]
Should be fixed as of https://github.com/Jannyboy11/InvSee-plus-plus/releases/tag/v0.19.8. If it works for you, can you close the issue please?

**Comment by golfista** [comment]
Sure, thank you so much.

**Comment by Jannyboy11** [comment]
You closed the issue before the artifacts were available o.0

**Comment by Jannyboy11** [comment]
It seemed I didn't push my changes to GitHub yet.. >.< Could you redownload the plugin from that link (should be available in ~30 minutes)?
