### ISSUE TITLE
Disappearing placeholders

### ISSUE THREAD

**Issue by Ompyl** [Jannyboy11/InvSee-plus-plus#78]
When doing an invsee the placeholder item I click onto vanishes, when doing it a second time, all placeholder items vanish

**Comment by Jannyboy11** [comment]
That is the intended behaviour. Most slots occupied by placeholders are actual slots where player itmes can go. The only placeholder for which this isn't true is the 'inaccessible' placeholder. I can look into whether I can make it so these won't disappear, but this might be hard since all placeholders are implemented using packets.

**Comment by Ompyl** [comment]
ok

**Comment by Ompyl** [comment]
but other than that, this plugin is the best one out there!
