### ISSUE TITLE
API ?

### ISSUE THREAD

**Issue by MrClean1337** [Jannyboy11/InvSee-plus-plus#8]
Hello, nice plugin !
Gotta question here! No issue :D

Is there any documentation about the API of this plugin?
Or is there an API at all? 

Something like InvseePlusPlusAPI.openInv (player, player) .. ?

Thanks 👍

**Comment by MrClean1337** [comment]
Thank you! No more questions!

**Comment by Jannyboy11** [comment]
Alright. I'll close this issue when the api is stable and documented.

**Comment by Jannyboy11** [comment]
I've refactored the InvseeAPI class today, there are now alternative methods to spectate inventories:
`mainSpectatorInventory` and `enderSpectatorInventory`.

These return `CompletableFuture<SpectateResponse<MainSpectatorInventory>>` and `CompletableFuture<SpectateResponse<EnderSpectatorInventory>>` instead of futures of optionals.
`SpectateResponse` is preferred over `Optional` because Optional doesn't provide a good way of indicating how creating the inventory failed - SpectateResponse allows me to do just that. For example:
```java

InvseeAPI invseeApi = //get via the same method as before
Player adminPlayer = //...

CompletableFuture<SpectateResponse<MainSpectatorInventory>> future = invseeApi.mainSpectatorInventory("Notch", "Notch's Inventory");

future.whenComplete((response, error) -> {
    if (error != null) {
        if (response.isSuccess()) { //this is just like Optional.isPresent()
             MainSpectatorInventory spectatorInventory = response.getInventory();
             adminPlayer.openInventory(spectatorInventory);
        } else {
             NotCreatedReason reason = response.getReason();
             //either the target does not exist, or the target has the excempt permission.
        }
    } else {
        //handle error
    }
});
```
`NotCreatedReason` is a sum-type that currently has three possible implemenations: `TargetHasExemptPermission` or `TargetDoesNotExist`. More may be added in the future. Unfortunately I couldn't make `NotCreatedReason` a sealed class, because I need to remain compatible with Java 11 still.

These new methods of creating spectator inventories are preferred over the old ones, the old ones will eventually be removed.

**Comment by Jankoekenpan** [comment]
The api is now somewhat documented on the wiki!
https://github.com/Jannyboy11/InvSee-plus-plus/wiki
